### ISSUE TITLE
Create schedule to display 5 phases

### ISSUE THREAD

**Issue by karthy1104** [mrc-india-csr/katha-utsav-2021-registration#12]
As a user 
I want to view the various phases
So that I can infer the following details 
 - Date (will provide the date on which the phase will be completed) 
 - Phase number (will provide the Phase numbers)
 - Text (a brief description about the phase)

GIVEN I am in the Katha page
WHEN I am in the Schedule section
THEN I should see the section header "Schedule" with 5 phases

GIVEN I am in the Katha page
WHEN I am in the Schedule section
THEN each phase should have the below information
 - Date (Format DD Mon)
 - Phase # (Need only 5 Phases for this competition, need to build this as configurable)
 - Text (A brief description about the phase will be displayed)

Dev Comp - 09/01

**Comment by sseenivasan89** [comment]
@Hemanth10081999 @karthy1104 - what is the actual date and months 
![image](https://user-images.githubusercontent.com/44080743/132317457-3192461a-05b8-4aeb-a7ac-27e68909488d.png)

**Comment by DineshKumarVasudevan** [comment]
The dates shall be provided later in time.
@sseenivasan89 @Hemanth10081999 @PadhmanathanR
