### ISSUE TITLE
Schema Design

### ISSUE THREAD

**Issue by DineshKumarVasudevan** [mrc-india-csr/katha-utsav-2021-registration#9]
As a DB owner
I want to design a schema for KATHA UTSAV 2021
so that the data can be stored in a relational DB.

Acceptance Criteria:
Given all the required data points for the event is collected
When a DB is available
Then create the schema that can accommodate all the data. 

Unable to connect to the server - Kamali to confirm after api test.

**Comment by SalmahSY** [comment]
Senthil N will create a schema and give it to me for further development
